# Generated by Django 4.2.14 on 2024-08-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='mobile',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='mobile',
        ),
        migrations.AddField(
            model_name='doctor',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time1',
            field=models.TimeField(null=True),
        ),
    ]
